### ISSUE TITLE
Slack Channels?

### ISSUE THREAD

**Issue by jxadro** [open-cluster-management-io/community#1]
Hi,

Is there any public slack channel where users could make questions?

Thank you.

**Comment by juliana-hsu** [comment]
Hi, 
We have a request out to create a public slack channel.  It should be coming soon.  Thanks.

**Comment by juliana-hsu** [comment]
Our Slack channel is live at #open-cluster-mgmt channel on http://kubernetes.slack.com or direct link https://kubernetes.slack.com/archives/C01GE7YSUUF

**Comment by mikeshng** [comment]
Slack channel is now available.
