### ISSUE TITLE
TAG-Runtime presentation/discussion

### ISSUE THREAD

**Issue by raravena80** [open-cluster-management-io/community#107]
Hello Open Cluster Management team,

I'm one of the co-chairs of the CNCF TAG-Runtime. I'm reaching out and I think it would be great for you to present/discuss the project at one of our meetings. For example, a general overview of the project or/and a demo.

Feel free to add it to our [agenda](https://bit.ly/cncf-tag-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by yue9944882** [comment]
@raravena80 thanks, i just added OCM to the agenda on 16th Dec's meeting. will do the presentation at that time.

**Comment by raravena80** [comment]
@yue9944882 Is it possible to present on Dec 2nd instead, that way you get the full hour for the presentation? (There is another agenda items on Dev 16th)

**Comment by raravena80** [comment]
@yue9944882 following up here 😄

**Comment by yue9944882** [comment]
@raravena80 hey apologies for the delay. but we can schedule the presentation to the next meeting time after 16th, i didnt see the next schedule in the doc tho.

**Comment by raravena80** [comment]
Folks, following up here. Would you like to present on Jan 20th?  Thanks

**Comment by yue9944882** [comment]
@raravena80 yeah i just added the presentation to the date

**Comment by yue9944882** [comment]
@raravena80 oddly no one's in the meeting, am i missing anything?

**Comment by raravena80** [comment]
@yue9944882 I couldn't find you on Slack. Thanks for presenting today, looking forward to seeing the project grow.

**Comment by apphe** [comment]
Thanks both @raravena80 and @yue9944882 . Can we mark this issue as done and close it? Thanks!

**Comment by raravena80** [comment]
@apphe of course. Thanks!
