### ISSUE TITLE
Apply to be an OCM member

### ISSUE THREAD

**Issue by morvencao** [open-cluster-management-io/community#108]
### Community Participant

Asked some questions and replied some messages on slack channel "#open-cluster-mgmt"

### Initialized some features/enhancement and contribute ideas. Contributed some bug fixed at placement, registration, community.

- [set common env and reduce the kube context switch](https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/118)
- [add copy to clipboard function for code snippets](https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/143)
- [add guideline for api changes](https://github.com/open-cluster-management-io/community/pull/27)

### Requirements

- Enabled [two-factor authentication] on their GitHub account
  Yes

- Have made multiple contributions to the project or community. Contribution may include, but is not limited to:
  * Authoring or reviewing PRs on GitHub
  * Filing or commenting on issues on GitHub
  * Contributing to documentation, blogs, tutorials
  * Contributing to test automation

- Contributing to community discussions (e.g. meetings, Slack, mailing list discussion)
  Yes

- Subscribed to [https://groups.google.com/g/open-cluster-management]
  Yes

- Have read the [contributor guide]
  Yes

- Actively contributing to 1 or more subprojects.
  Yes

- Sponsored by 2 reviewers. Note the following requirements for sponsors:

  * Sponsors must have close interactions with the prospective member, e.g. code/design/proposal review, coordinating on issues, etc.
  * Sponsors must be reviewers or approvers in at least 1 OWNERS file in any repo in the [Open-Cluster-Management org], or the org they are sponsoring for.
  * An approver/reviewer in the [Open-Cluster-Management org] may sponsor someone for the [Open-Cluster-Management org]
or any of the related [Open-Cluster-Management GitHub organizations]; as long as it's a project they're involved with.
  * Sponsors must be from multiple member companies to demonstrate integration across the community.
  
   Yes  @qiujian16 ^^

- [Open an issue][membership request] against the Open-Cluster-Management/community repo

- Ensure your sponsors are @mentioned on the issue

- Complete every item on the checklist

  * Make sure that the list of contributions included is representative of your work on the project.
  Yes

- Have your sponsoring reviewers reply confirmation of sponsorship: +1

- Once your sponsors have responded, your request will be reviewed by the [Open-Cluster-Management GitHub Admin team].

**Comment by morvencao** [comment]
@qiujian16 ^

**Comment by hchenxa** [comment]
+1

**Comment by qiujian16** [comment]
invitation sent. Thanks!
