### ISSUE TITLE
New repository: helm-charts

### ISSUE THREAD

**Issue by mikeshng** [open-cluster-management-io/community#114]
We should create a repo call "helm-charts" or "charts" to provide more openness and visibility to OCM related helm chart(s) that are referenced on our website. For example, https://open-cluster-management.io/getting-started/integration/cluster-proxy

It will be nice if the repo can also host the charts and have CICD to manage the release lifecycle of the chart as well.
If we follow the guide in 
https://helm.sh/docs/topics/chart_repository/#github-pages-example
https://helm.sh/docs/howto/chart_releaser_action
we might be able to accomplish this but there is some concerns regarding the frequency of the release. 

Before we create repo and start using the above GitHub action, we should investigate a bit more and see if the tooling matches our need. One of the criteria is, if it can reliability replace an existing release with the same version number.

**Comment by yue9944882** [comment]
+1

**Comment by mikeshng** [comment]
Update: The Helm chart releaser GitHub action doesn't allow for the same version of the chart. At minimal it needs a patch version increment.

But I think regardless of if we end up using the chart releaser or not, we should still have this repo to host the source code of some of our Helm charts to bring more openness/visibility to the community.

**Comment by qiujian16** [comment]
I would want to clarify what content should be put in this repo. I think it will include:
1. helm charts of addons maintained in this repo (subscription/policy/cluster-proxy etc)
2. helm charts of external addons (submariner/clusternet etc)

With that we could have an addon installation flow:

```
$ helm install addon-foo
$ clusteradm enable addon-foo --cluster cluster1
```

I am not sure about the basic installation of ocm. Given it can be done by clusteradm already.

**Comment by mikeshng** [comment]
> I would want to clarify what content should be put in this repo. I think it will include: ...

I agree with you Qiu Jian.

**Comment by ryanzhang-oss** [comment]
The convention is to embed the chart with the repo it packages. I am not sure if we need another repo for this
