### ISSUE TITLE
refactor the e2e of clusteradm to make it more scalable

### ISSUE THREAD

**Issue by zhiweiyin318** [open-cluster-management-io/community#118]
the e2e (functional tests) of clusteradm is implemented by shell scripts. it is not easy to add new cases.
 we need refactor it to make it more scalable.

**Comment by ycyaoxdu** [comment]
@apphe @zhiweiyin318 maybe we can close this issue now.

**Comment by zhiweiyin318** [comment]
/close 
thanks for the contribution. @ycyaoxdu
