### ISSUE TITLE
Use the klusterlet addon framework for grc managed cluster components

### ISSUE THREAD

**Issue by gparvin** [open-cluster-management-io/community#122]
Move the grc resources from the klusterlet addon into a new grc addon.  This lets grc use the klusterlet addon framework features consistently instead of being provided in a custom bundle of addons.

**Comment by dhaiducek** [comment]
@apphe FYI: This is ready for the `v0.8.0` release. The open PR covers website doc updates that can't merge until a release has been cut.

**Comment by apphe** [comment]
@dhaiducek Thanks for the update!
