### ISSUE TITLE
New repo: `governance-policy-addon-controller`

### ISSUE THREAD

**Issue by dhaiducek** [open-cluster-management-io/community#135]
We'd like to create an additional repo, `governance-policy-addon-controller` in order to manage and simplify the deployment of the GRC addon.

Related issue:
- https://github.com/open-cluster-management-io/community/issues/122

**Comment by dhaiducek** [comment]
(I'll create an enhancement issue for this shortly...)

**Comment by mikeshng** [comment]
+1

However, I am not an org owner who can create repo. I am going to unassign myself and assign Josh who has permission to do so.

**Comment by qiujian16** [comment]
@dhaiducek please also suggest who will be the owner of this repo

**Comment by dhaiducek** [comment]
Sure! It would fall under policy, so it would have an OWNERS file similar to [this one](https://github.com/open-cluster-management-io/governance-policy-propagator/blob/main/OWNERS) (from the propagator), and would similarly be administered by mprahl, gparvin, JustinKuli, and myself.

**Comment by qiujian16** [comment]
hrm, that looks a very long list. I would suggest a shorter owner file initially. may start with mprahl, gparvin, JustinKuli, and dhaiducek initially.

**Comment by qiujian16** [comment]
repo created https://github.com/open-cluster-management-io/governance-policy-addon-controller

/close

**Comment by dhaiducek** [comment]
Sounds good--thanks so much @qiujian16!

**Comment by dhaiducek** [comment]
Would you please also give me admin permissions on it?

**Comment by qiujian16** [comment]
added
