### ISSUE TITLE
New repo: `helm-charts`

### ISSUE THREAD

**Issue by yue9944882** [open-cluster-management-io/community#136]
previously @mikeshng presented a demo for automating the chart packages based on the helm's official tutorial: https://helm.sh/docs/howto/chart_releaser_action/.  i think it's about time to start exercising the chart management workflow in OCM.

**Comment by qiujian16** [comment]
+1

**Comment by mikeshng** [comment]
+1

**Comment by qiujian16** [comment]
@yue9944882 would you also suggest who would be the owner of this new repo?

**Comment by yue9944882** [comment]
plz grant @zhiying-lin and me admin access so that we can configure secrets for pushing the charts

**Comment by qiujian16** [comment]
repo created. @zhiying-lin  I am adding you as the ocm org member, please help to accept that. Thanks!

**Comment by yue9944882** [comment]
@qiujian16 can we close this thread?
