### ISSUE TITLE
Cut release branches for v0.6.0+

### ISSUE THREAD

**Issue by mikeshng** [open-cluster-management-io/community#142]
OCM repos only use tags for now but this is a problem when we want to release a fix for a previous released version. 

Based on the community discussion, we should cut a release for v0.6.0. For the future releases, (ie: v0.7.0) we will be cutting branches as well.

**Comment by yue9944882** [comment]
this will be helpful thanks! @mikeshng

**Comment by zhujian7** [comment]
@mikeshng now we have [these branches](https://github.com/open-cluster-management-io/ocm/branches/all), can we close this issue?
