### ISSUE TITLE
New repo: ocm-vscode-extension 

### ISSUE THREAD

**Issue by ilan-pinto** [open-cluster-management-io/community#144]
We'd like to transfer a repo to the OCM org, ocm-vscode-extension in order to BUILD and simplify the development and deployment usage of OCM.
this extension must have its own designated repo due to vscode marketplace requirements.  

Related issue:
https://github.com/open-cluster-management-io/OCM/issues/41#issuecomment-1081638185

**Comment by mikeshng** [comment]
Thanks @ilan-pinto for your work. I think this is a really good idea. Please provide the repo URL when you are ready.

**Comment by ilan-pinto** [comment]
link to the current repo https://github.com/ilan-pinto/ocm-vscode-extension

**Comment by mikeshng** [comment]
+1

/assign qiujian16

/assign yue9944882

Hi Qiu Jian and Min, WDYT?

**Comment by qiujian16** [comment]
this sounds a great idea. I would suggest we bring this to the community meeting. Also it will be helpful to describe what is the planned functions for this tool.

**Comment by ilan-pinto** [comment]
some features:  
- executing clusteradm commands
- querying deployed application status crd's   
- one-click creating a kind ocm cluster env for a local test or evaluating OCM 

and more

**Comment by yue9944882** [comment]
sounds like a great feature! i regret to migrate from vs-code to goland a few yrs ago. at that time go vendor mgmt is a mess and vs-code loads/indexs large project like k8s extremely slowly, goland has a better performance so i changed my IDE 🥲 will surely try the extension!

**Comment by qiujian16** [comment]
will create a repo for this next week. @ilan-pinto would you let me know who will be the owner of this repo?

**Comment by ilan-pinto** [comment]
Hi @qiujian16 
you can make Tomer (@TomerFi), Vladimir(@ vbelouso ), and I maintainers.
also feel  free to add yourself

**Comment by qiujian16** [comment]
repo created.

@TomerFi and @vbelouso, I also add you into the org as member. Please accept the invitation. Thanks
