### ISSUE TITLE
New repo: multicluster-mesh-addon

### ISSUE THREAD

**Issue by morvencao** [open-cluster-management-io/community#149]
We would like to create an additional repo `multicluster-mesh-addon` to manage multicluster service mesh on OCM as an addon.
Related issue: https://github.com/open-cluster-management-io/OCM/issues/34

/assign @mikeshng @qiujian16

**Comment by mikeshng** [comment]
+1

Would you be able to do a quick presentation in our community meeting next week?

**Comment by morvencao** [comment]
Sure, I added the topic in the meeting agenda.

**Comment by morvencao** [comment]
@mikeshng Who can help to create the new repo after we have shown this in weekly meeting?

**Comment by qiujian16** [comment]
I will do that after back from the vacation :)

**Comment by qiujian16** [comment]
@morvencao who will be the maintainer of this repo?

**Comment by morvencao** [comment]
@qiujian16 Any requirements for the maintainer? I can maintain this repo.

**Comment by qiujian16** [comment]
the only requirement is the maintainer should be the member of ocm org. And It would be better to have at least 2 maintainers.

**Comment by qiujian16** [comment]
done https://github.com/open-cluster-management-io/multicluster-mesh

/close
