### ISSUE TITLE
Meeting information not in expected location

### ISSUE THREAD

**Issue by larsks** [open-cluster-management-io/community#15]
The README says:

> Meeting dial-in details, meeting notes and agendas are announced and published to the open-cluster-management mailing list on Google Groups

...but there's no information in the google group; the meeting details appear to be on the project board instead. Update the README? Or post to the mailing list?

**Comment by juliana-hsu** [comment]
Apologies we were late in posting this:  https://groups.google.com/g/open-cluster-management

**Comment by mikeshng** [comment]
google group and meeting info is now being posted.
