### ISSUE TITLE
🏕 Alibaba Summer of Code (ASOC) 2022 

### ISSUE THREAD

**Issue by yue9944882** [open-cluster-management-io/community#152]
Welcome to the open-source world! If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and code with us! 💻

Alibaba Summer of Code is a global program focused on engaging students directly in open source software development. Under the guidance of the mentor in the Alibaba open source project, students can experience software development in the real world. Alibaba Summer of code will begin from May 30th to September 1st. Students can use the summertime to participate in the open-source project and work with the core members of the project.

This is a master issue to track the progress and result of [Alibaba Summer of Code 2022](https://opensource.alibaba.com/asoc2022).

### 🎊 What you can get?
On this exclusive developer journey, students will have the opportunity to:

Participate in the top projects of the International Open Source Foundation
Get a scholarship from Alibaba
Obtain an open-source contributor certificate
Get a fast pass of Alibaba Internship
Get your code adopted and used by the open-source project！

### 👨‍🏫 Our Mentor
Min Jin (@[yue9944882](https://github.com/yue9944882) ), OCM maintainer

⏱ Timeline
![image](https://user-images.githubusercontent.com/12049380/170533002-6abd36df-17d6-4075-b8a0-f9af53dc4d51.png)

🚀 Apply Now!
1.Browse open idealist here:

- #153
- #154

2.Upload your CV and project proposal via ASOC 2022 official website

🐚 Contact the Organizer
If you have any questions, visit the event website: [opensource.alibaba.com/asoc2022](https://opensource.alibaba.com/asoc2022)

Email address: [opensource@alibaba-inc.com](mailto:opensource@alibaba-inc.com)

**Comment by yhx-coder** [comment]
请问只能用go完成吗

**Comment by mikeshng** [comment]
Completed. See the presentation for more details: https://www.youtube.com/watch?v=j7ycK5zaaXA
