### ISSUE TITLE
New repo: `governance-policy-nucleus`

### ISSUE THREAD

**Issue by JustinKuli** [open-cluster-management-io/community#157]
To implement the [core-policy-module proposal](https://github.com/open-cluster-management-io/enhancements/tree/main/enhancements/sig-policy/54-core-policy-module) from https://github.com/open-cluster-management-io/enhancements/pull/55, we would like a new repo named `governance-policy-nucleus`. As described in the proposal, this repo will contain common API validation, structs, and methods that multiple policy controllers can use. 

The OWNERS file should likely start with the same contributors as the [governance-policy-addon-controller OWNERS file](https://github.com/open-cluster-management-io/governance-policy-addon-controller/blob/main/OWNERS).

If it would be easier, I could initialize the repository under my name and try to transfer it to this organization, just let me know.

/assign @qiujian16 @jnpacker

**Comment by qiujian16** [comment]
created

/close
