### ISSUE TITLE
Suggestion: Include a link to the community release plans/roadmap from the OCM repo

### ISSUE THREAD

**Issue by nelsonjean** [open-cluster-management-io/community#158]
Currently the community release info is in [OCM Community webpage](https://open-cluster-management.io/)->[Community](https://open-cluster-management.io/community/). I would like to propose we add a direct link to the community release info from the [OCM repo](https://github.com/open-cluster-management-io/community) since there's an affinity between the Github issues and the community releases in which they would be resolved in.

**Comment by mikeshng** [comment]
Thank you for the suggestion @nelsonjean 

I will create a PR later for this.

/assign mikeshng

**Comment by nelsonjean** [comment]
Thanks Mike...looks good!
