### ISSUE TITLE
membership request

### ISSUE THREAD

**Issue by promacanthus** [open-cluster-management-io/community#160]
# Application

## Community Participant

Recently, I began to study OCM and contributed as following:

- Initialized some features/enhancements and contributed some ideas.
- Contributed some features at [api](https://github.com/open-cluster-management-io/api), [registration-operator](https://github.com/open-cluster-management-io/registration-operator), [registration](https://github.com/open-cluster-management-io/registration) and [clusteradm](https://github.com/open-cluster-management-io/clusteradm).
- Fixed some bugs at [api](https://github.com/open-cluster-management-io/api) and [registration](https://github.com/open-cluster-management-io/registration).

The Multi Cluster Management platform of [XiaoHongShu](https://www.xiaohongshu.com/en) is builded based on OCM and I hope to be bridge between OCM community and my company.

Thank you!

## Requirements

Have made multiple contributions to the project or community. Contribution may include, but is not limited to:

- https://github.com/open-cluster-management-io/api/issues/165
- https://github.com/open-cluster-management-io/api/pull/166
- https://github.com/open-cluster-management-io/api/pull/168
- https://github.com/open-cluster-management-io/api/pull/169
- https://github.com/open-cluster-management-io/registration-operator/pull/258
- https://github.com/open-cluster-management-io/registration/pull/259
- https://github.com/open-cluster-management-io/clusteradm/pull/250

### Checklists

- [x] Enabled [two-factor authentication] on their GitHub account.
- [x] Contributing to community discussions (e.g. meetings, Slack, mailing list discussion).
- [x] Subscribed to [https://groups.google.com/g/open-cluster-management].
- [x] Have read the [contributor guide].
- [x] Actively contributing to 1 or more subprojects.

### Sponsors

- @qiujian16 

---
# Instructions

1. [Open an issue][membership request] against the [Open-Cluster-Management/community repo](https://github.com/open-cluster-management-io/community).
2. Ensure your sponsors are @mentioned on the issue.
3. Complete every item on the checklist.
4. Make sure that the list of contributions included is representative of your work on the project.
5. Have your sponsoring reviewers reply confirmation of sponsorship: +1
6. Once your sponsors have responded, your request will be reviewed by the [Open-Cluster-Management GitHub Admin team](https://github.com/orgs/open-cluster-management-io/people).

Sponsored by 2 reviewers. Note the following requirements for sponsors:

- Sponsors must have close interactions with the prospective member, e.g. code/design/proposal review, coordinating on issues, etc.
- Sponsors must be reviewers or approvers in at least 1 OWNERS file in any repo in the [Open-Cluster-Management org](https://github.com/open-cluster-management-io), or the org they are sponsoring for.
- An approver/reviewer in the [Open-Cluster-Management org](https://github.com/open-cluster-management-io) may sponsor someone for the [Open-Cluster-Management org](https://github.com/open-cluster-management-io)
or any of the related [Open-Cluster-Management GitHub organizations](https://github.com/open-cluster-management-io); as long as it's a project they're involved with.
- Sponsors must be from multiple member companies to demonstrate integration across the community.

**Comment by qiujian16** [comment]
invitation sent. thanks for your contribution!
