### ISSUE TITLE
Prerequisite for consolidating some policy addon repos

### ISSUE THREAD

**Issue by mprahl** [open-cluster-management-io/community#164]
The Policy SIG is requesting a new GitHub repo called `governance-policy-syncer` in order to consolidate the `governance-policy-spec-sync`, `governance-policy-template-sync`, and `governance-policy-status-sync` controllers.

This effort is to reduce the overall number of repos in the GitHub organization as well as reduce the footprint of the Policy addon.

**Comment by mikeshng** [comment]
+1 

I think this is a great idea.

/assign @qiujian16

**Comment by mikeshng** [comment]
@mprahl we briefly discuss the possibility of renaming repos to better organize the OCM org. Do you think it makes sense to append `-addon` at the end of the new repo name?

**Comment by mprahl** [comment]
> @mprahl we briefly discuss the possibility of renaming repos to better organize the OCM org. Do you think it makes sense to append `-addon` at the end of the new repo name?

I'd be also fine with `syncer-policy-addon` or `policy-syncer-policy-addon`.

**Comment by qiujian16** [comment]
just for curiosity. for policy-propagator, config-policy-controller and policy-addon-controller, is it possible to also consolidate them? since we only have one policy syncer after this.

**Comment by mprahl** [comment]
> just for curiosity. for policy-propagator, config-policy-controller and policy-addon-controller, is it possible to also consolidate them? since we only have one policy syncer after this.

The syncer would be responsible for the managed cluster component that syncs from (policies) and to (policy status) the Hub. This is represented as the `governance-policy-framework` addon.

I think there is a possibility to combine the Policy Propagator and Addon controller since those are both Hub components, but it's not currently planned.

As for the config-policy-controller, it is a separate addon that handles evaluating/enforcing `ConfigurationPolicy` objects on the managed cluster. It can work independently of the other components, but it doesn't really make sense to do that if you are using OCM. I like how it's a separate repo since it's structured as a microservice that is distinctive from the rest of the policy components.

**Comment by qiujian16** [comment]
ok could we decide the name of each these repos, using "-addon" as postfix

**Comment by mprahl** [comment]
> ok could we decide the name of each these repos, using "-addon" as postfix

I'd like to defer the renaming of existing repos for now since there is coordination that would need to happen on our end.

For now, could you please create a new repo called `governance-policy-framework-addon` which will consolidate the repos I mentioned in the original comment?

**Comment by qiujian16** [comment]
created. I would suggest putting policy-propagator and policy-addon-controller also in this repo. It is fine to have hub/spoke side code together.

**Comment by mprahl** [comment]
@qiujian16 thanks for creating it!. Could you please give the Policy SIG admin access on the new repo?
