### ISSUE TITLE
Epic: Improve the code quality of OCM repos

### ISSUE THREAD

**Issue by elgnay** [open-cluster-management-io/community#166]
In order to improve the code quality of ocm repos, it's necessary to
- [x] https://github.com/open-cluster-management-io/community/issues/167
- [x] https://github.com/open-cluster-management-io/community/issues/168

**Comment by xuezhaojun** [comment]
What we have done:
1. Using [coverage.io](https://codecov.io/) to calculate coverage scores.
2. Set up dynamic bars to protect coverage drop.
3. Consolidate code into one repo -- [ocm](https://github.com/open-cluster-management-io/ocm); its coverage score is 60% now. 

To balance developing speed and quality, we decide to mark this Epic as done and keep improving our code coverage in the future refactor.
