### ISSUE TITLE
Increase the code coverage of OCM repos to 70%

### ISSUE THREAD

**Issue by elgnay** [open-cluster-management-io/community#167]
The code coverage of the following repos should be more than 70%:
- [ ] [registration](https://github.com/open-cluster-management-io/registration) (55.1%)
- [ ] [work](https://github.com/open-cluster-management-io/work) (69.4%)
- [ ] [registration-operator](https://github.com/open-cluster-management-io/registration-operator) (66.9%)
- [x] [placement](https://github.com/open-cluster-management-io/placement) (70.1%)
- [ ] [managed-serviceaccount](https://github.com/open-cluster-management-io/managed-serviceaccount) (2.1%)
- [ ] [cluster-proxy](https://github.com/open-cluster-management-io/cluster-proxy) (1.2%)

**Comment by pshickeydev** [comment]
@elgnay how are you calculating this coverage? Asking as a follow up to https://github.com/open-cluster-management-io/OCM/issues/85

**Comment by xuezhaojun** [comment]
@pshickeydev We're using [codecov.io](https://codecov.io/) to calculate the coverage.
