### ISSUE TITLE
New repo: `addon-contrib`

### ISSUE THREAD

**Issue by yue9944882** [open-cluster-management-io/community#170]
To create a new repo named `addon-contrib` for hosting the open-telemetry addon which is an outcome of the OSPP summer camp project:

https://summer-ospp.ac.cn/#/org/orgdetail/139c2402-194c-42a0-95e9-ab23885384cb/

/assign @qiujian16

**Comment by mikeshng** [comment]
Should we use the name `open-telemetry-addon` to better reflect the content of the repo?

**Comment by qiujian16** [comment]
I think the intention is to host multiple addons in this repo that are not quite mature yet.
