### ISSUE TITLE
New repo: argocd-pull-integration

### ISSUE THREAD

**Issue by chenz4027** [open-cluster-management-io/community#173]
We would like to create an additional repo `argocd-pull-integration` for enhancing ArgoCD and OCM integration with the pull model resource delivery mechanism. Eventually, we are hoping to donate this repo to the ArgoCD Lab organization https://github.com/argoproj-labs by going through the process provided in https://github.com/argoproj/argoproj/blob/master/community/ecosystem-projects.md

Related issue: https://github.com/open-cluster-management-io/OCM/issues/70
Design doc: https://docs.google.com/document/d/1X1Sce55bGUsyFCJkcefb8E4_K7tcpwRTwKD8aXnKS7Q/edit
Proposed repo content: https://github.com/mikeshng/argocd-pull-integration
Related videos: https://www.youtube.com/watch?v=eNDJy58gIJ0 and https://www.youtube.com/watch?v=SLdcNgs603I and https://www.youtube.com/watch?v=z7mEz8i91xM

/assign @qiujian16 @mikeshng

**Comment by mikeshng** [comment]
+1

**Comment by qiujian16** [comment]
could we clarify the diff from https://github.com/open-cluster-management-io/multicloud-integrations? Could we just rename the multicloud-integrations to argocd-integration? Or that will impact our plan to move it into argocd ecosystem?

**Comment by mikeshng** [comment]
Hi @qiujian16 

> could we clarify the diff from https://github.com/open-cluster-management-io/multicloud-integrations?

The main difference is we are not planning to migrate that repo to the Argo lab org. The newly proposed repo is hopefully destined to be migrated. If the ArgoCD community refuses the new repo then we will merge the new proposed repo into the existing multicloud-integrations repo.

> Could we just rename the multicloud-integrations to argocd-integration? 

I think we always meant for that repo to have more integrations and not just ArgoCD. We are also hoping to get the argocd-pull-integration repo accepted into the Argo lab org first and then we can evaluate what else make sense to migrate over.

> Or that will impact our plan to move it into argocd ecosystem?

Yes, exactly. We think it will impact our plan to move to Argocd ecosystem. We want to start with the less Openshift centric pull controller first. 

Once we are successfully onboarded to the argocd ecosystem, we can archive the argocd-pull-integration repo.

**Comment by qiujian16** [comment]
ok, that makes sense. Thanks. I am on board.

**Comment by mikeshng** [comment]
Forgot to mention the OWNERS file can start with this one https://github.com/mikeshng/argocd-pull-integration/blob/main/OWNERS

If you think that is too many users then:
```
approvers:
- jnpacker
- mikeshng
- xiangjingli
reviewers:
- jnpacker
- mikeshng
- xiangjingli
```

Thanks.

**Comment by mikeshng** [comment]
@qiujian16 could you please create the repo whenever you have some cycles? Thanks. CC @xiangjingli

**Comment by qiujian16** [comment]
my bad, will do it today..

**Comment by qiujian16** [comment]
https://github.com/open-cluster-management-io/argocd-pull-integration created. @mikeshng would you help to finish the logistic part? owner files, security.md, dco github action etc..and close this one when they are done. Thanks!

**Comment by mikeshng** [comment]
Done as required.

/close
