### ISSUE TITLE
New repository: `cluster-permission` Multi-cluster RBAC management

### ISSUE THREAD

**Issue by mikeshng** [open-cluster-management-io/community#179]
see the proposal at: https://github.com/open-cluster-management-io/enhancements/pull/91

CC @qiujian16 @jnpacker

**Comment by mikeshng** [comment]
Owners file:

```
approvers:
- jnpacker
- mikeshng
- xiangjingli
reviewers:
- jnpacker
- mikeshng
- xiangjingli
```

**Comment by qiujian16** [comment]
do we need to wait until the proposal is merged?

**Comment by mikeshng** [comment]
Yes, you are right we should wait.
