### ISSUE TITLE
Migrate Build Infrastructure from Travis to Prow

### ISSUE THREAD

**Issue by ray-harris** [open-cluster-management-io/community#18]
Most OCM components are built using Travis which limits the ability of external collaborators to submit pull requests that are automatically tested.

To address this, we are working to migrate the build infrastructure from Travis to OpenShift CI Prow. This will allow us to approve external collaborators to open PRs that can be automatically tested before they are reviewed and merged.

The work currently consists of these tasks:

- [x] Develop a Prow based build harness extension to integrate Prow builds into to the ACM pipeline
- [x] Create a Prow image builder for Go
- [ ] Create a Prow image builder for NodeJS
- [ ] Unify our Travis and Prow build harness extensions to ease migration
- [ ] Develop Prow workflows to allow testing to use cluster pools to create multiple clusters during testing
- [ ] Develop a sample component as a template for migrating from Travis to Prow
- [ ] Document the steps needed to migrate a repo from Travis to Prow

The Prow based build harness extensions are here:
https://github.com/open-cluster-management/build-harness-ext-osci

The Prow image builder for Go is here (this is where the NodeJS image builder will be added as well):
https://github.com/open-cluster-management/image-builder

The Travis based build harness extensions are here (this is where the Prow based extensions will be integrated):
https://github.com/open-cluster-management/build-harness-extensions

There are a few OCM repos that were created in Prow. Those repos are configured here in OpenShift CI:
https://github.com/openshift/release/tree/master/ci-operator/config/open-cluster-management
https://github.com/openshift/release/tree/master/ci-operator/jobs/open-cluster-management

The Prow workflows will be here:
https://github.com/openshift/release/tree/master/ci-operator/step-registry/acm

Links to other relevant repos and documentation will be added as they are created.
This issue will be updated as work progress and plans are updated.

We anticipate this work being completed by the end of January 2021, but this is not a firm schedule and is subject to change.

**Comment by mikeshng** [comment]
This is done or no longer apply to the community repos (use github action).
