### ISSUE TITLE
Apply to be an OCM member

### ISSUE THREAD

**Issue by dockerymick** [open-cluster-management-io/community#180]
# Application

## Community Participant

Long time participant of the OCM community.
Contributed publicly and privately to the documentation, website, blogs and presentations.

I hope to continue my contribution to the OCM community as a member.

Thank you!

## Requirements

Have made multiple contributions to the project or community. Contribution may include, but is not limited to:

- https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/27
- https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/63
- https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/103

### Checklists

- [x] Enabled [two-factor authentication] on their GitHub account.
- [x] Contributing to community discussions (e.g. meetings, Slack, mailing list discussion).
- [x] Subscribed to [https://groups.google.com/g/open-cluster-management].
- [x] Have read the [contributor guide](https://github.com/open-cluster-management-io/community/blob/main/CONTRIBUTING.md).
- [x] Actively contributing to 1 or more subprojects.

### Sponsors

- @mikeshng

**Comment by mikeshng** [comment]
+1

/assign @qiujian16

**Comment by qiujian16** [comment]
invitation sent
/close
