### ISSUE TITLE
membership request 

### ISSUE THREAD

**Issue by Arhell** [open-cluster-management-io/community#181]
# Application
## Community Participant
Hi there,  i want to help with the site, fix bugs, accessibility and updates
## Requirements
PRs
https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/commits?author=Arhell
### Checklists

- [x] Enabled [two-factor authentication] on their GitHub account.
- [x]  Contributing to community discussions (e.g. meetings, Slack, mailing list discussion).
- [x] Subscribed to [https://groups.google.com/g/open-cluster-management].
- [x] Have read the [contributor guide](https://github.com/open-cluster-management-io/community/blob/main/CONTRIBUTING.md).
- [x] Actively contributing to 1 or more subprojects.

### Sponsors

- @mikeshng

**Comment by mikeshng** [comment]
+1

/assign @qiujian16

**Comment by qiujian16** [comment]
invitation sent
/close
