### ISSUE TITLE
Apply to become an OCM member

### ISSUE THREAD

**Issue by ydFu** [open-cluster-management-io/community#182]
# Application
## Community Participant
I have been actively contributing to the OCM community for a considerable period of time, and I am eager to apply for OCM membership. 
My aspiration is to make both public and private contributions through my involvement in documentation, website development, blogging, and presentation materials. 
This will enable me to further promote cloud-native technologies within the community and ensure a broader awareness among a wider audience.
  
## Requirements
Have made multiple contributions to the project or community. Contribution may include, but is not limited to:

- https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/377
- https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/378
- https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/379
- https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/381
- https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/382

### Checklists
* [x]  Enabled [two-factor authentication] on their GitHub account.
* [x]  Contributing to community discussions (e.g. meetings, Slack, mailing list discussion).
* [x]  Subscribed to [https://groups.google.com/g/open-cluster-management].
* [x]  Have read the [contributor guide](https://github.com/open-cluster-management-io/community/blob/main/CONTRIBUTING.md).
* [x]  Actively contributing to 1 or more subprojects.

### Sponsors
* @mikeshng

**Comment by mikeshng** [comment]
:+1: 

/assign @qiujian16

**Comment by qiujian16** [comment]
invitation sent, Thanks!
