### ISSUE TITLE
Application to become OCM member

### ISSUE THREAD

**Issue by zyjjay** [open-cluster-management-io/community#183]
# Application
## Community Participant
Made contributions to OCM repos like `config-policy-controller` and `governance-policy-framework-addon`. Looking forward to making more contributions to the OCM community as a member. 
 
## Requirements
Have made multiple contributions to the project or community. Contribution may include, but is not limited to:

* [ Empty label fields in policies are ignored #150 ](https://github.com/open-cluster-management-io/config-policy-controller/pull/150)
* [ Allow informonly configuration policies #75 ](https://github.com/open-cluster-management-io/governance-policy-framework-addon/pull/75)
* [ Create CRD for OperatorPolicy #155 ](https://github.com/open-cluster-management-io/config-policy-controller/pull/155)

### Checklists
* [x]  Enabled [two-factor authentication] on their GitHub account.
* [x]  Contributing to community discussions (e.g. meetings, Slack, mailing list discussion).
* [x]  Subscribed to [https://groups.google.com/g/open-cluster-management].
* [x]  Have read the [contributor guide](https://github.com/open-cluster-management-io/community/blob/main/CONTRIBUTING.md).
* [x]  Actively contributing to 1 or more subprojects.

### Sponsors
* @mprahl

**Comment by mikeshng** [comment]
+1

/assign @qiujian16

**Comment by qiujian16** [comment]
invitation sent
/close
