### ISSUE TITLE
OCM Member application

### ISSUE THREAD

**Issue by JeffeyL** [open-cluster-management-io/community#184]
# Application
## Community Participant
I have been actively contributing to the OCM project for some time now. I've done bugfixes and added features mostly centralized around the configuration policy controller, as well as the governance-policy-framework-addon.

My goal is to continue making contributions within this community.
 
## Requirements
Have made multiple contributions to the project or community. Contribution may include, but is not limited to:

* [ACM-6596: Initialize controller for OperatorPolicy #160](https://github.com/open-cluster-management-io/config-policy-controller/pull/160)
* [Bug: ACM-5052, Policy gets shortly into non-compliant state #144](https://github.com/open-cluster-management-io/config-policy-controller/pull/144)
* [ACM-3160: Invalid policy-templates array syntax leads to policy_system_errors_total incrementing #79](https://github.com/open-cluster-management-io/governance-policy-framework-addon/pull/79)
* [Bug: ACM-6803, Incorrect Policy does not show any validation errors and no status #83](https://github.com/open-cluster-management-io/governance-policy-framework-addon/pull/83)

### Checklists
* [x]  Enabled [two-factor authentication] on their GitHub account.
* [x]  Contributing to community discussions (e.g. meetings, Slack, mailing list discussion).
* [x]  Subscribed to [https://groups.google.com/g/open-cluster-management].
* [x]  Have read the [contributor guide](https://github.com/open-cluster-management-io/community/blob/main/CONTRIBUTING.md).
* [x]  Actively contributing to 1 or more subprojects.

### Sponsors
* @mprahl

**Comment by mikeshng** [comment]
+1

/assign @qiujian16

**Comment by qiujian16** [comment]
invitation sent

/close
