### ISSUE TITLE
Membership request

### ISSUE THREAD

**Issue by RokibulHasan7** [open-cluster-management-io/community#193]
# Application

## Community Participant

Made contributions to OCM repos like ocm, clusteradm, cluster-proxy. Looking forward to making more contributions to the OCM community as a member.

## Requirements

Have made multiple contributions to the project. Contribution may includes, but is not limited to:

### Contributions
- [Register ManifestWorkReplicaSet webhook when feature is enabled](https://github.com/open-cluster-management-io/ocm/pull/673)
- [Check if there any managed clusters exists before hub cleanup](https://github.com/open-cluster-management-io/clusteradm/pull/431)
- [Fix "log.SetLogger(...) was never called" in registration webhook](https://github.com/open-cluster-management-io/ocm/pull/488)

### Checklists

- [x] Enabled [two-factor authentication] on their GitHub account.
- [x] Contributing to community discussions (e.g. meetings, Slack, mailing list discussion).
- [x] Subscribed to [https://groups.google.com/g/open-cluster-management].
- [x] Have read the [contributor guide](https://github.com/open-cluster-management-io/community/blob/main/CONTRIBUTING.md).
- [x] Actively contributing to 1 or more subprojects.

## Sponsors

- @zhujian7

**Comment by zhujian7** [comment]
+1 
@RokibulHasan7 thanks for all your contributions!
/cc @qiujian16

**Comment by qiujian16** [comment]
thanks! invitation sent.
