### ISSUE TITLE
Deploy the subscription operators to managed cluster failed on OKD

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/community#43]
Run `make deploy-community-managed` as [this document](https://open-cluster-management.io/getting-started/integration/app-lifecycle/#install-from-source) said and got an error when downloading "build-harness-bootstrap".

fixed it after deleted `token ${GITHUB_TOKEN}'`  in this line: https://github.com/open-cluster-management/multicloud-operators-subscription/blob/59b66a70ce1b02a243db9140c917e7caaa209b09/Makefile#L67
```
-include $(shell curl -H 'Authorization: token ${GITHUB_TOKEN}' -H 'Accept: application/vnd.github.v4.raw' -L https://api.github.com/repos/open-cluster-management/build-harness-extensions/contents/templates/Makefile.build-harness-bootstrap -o .build-harness-bootstrap; echo .build-harness-bootstrap)
```

Maybe another approach is considering whether GITTHUB_TOKEN existed as [governance-policy-framework](https://github.com/open-cluster-management/governance-policy-framework.git) did:
```
ifndef GITHUB_TOKEN
-include $(shell curl -H 'Accept: application/vnd.github.v4.raw' -L https://api.github.com/repos/open-cluster-management/build-harness-extensions/contents/templates/Makefile.build-harness-bootstrap -o .build-harness-bootstrap; echo .build-harness-bootstrap)
else
-include $(shell curl -H 'Authorization: token ${GITHUB_TOKEN}' -H 'Accept: application/vnd.github.v4.raw' -L https://api.github.com/repos/open-cluster-management/build-harness-extensions/contents/templates/Makefile.build-harness-bootstrap -o .build-harness-bootstrap; echo .build-harness-bootstrap)
endif
```

**Comment by mikeshng** [comment]
`export TRAVIS_BUILD=0` should take care of this issue as well. Adding a PR to the website.

**Comment by mikeshng** [comment]
Hi @xuezhaojun 

https://open-cluster-management.io/getting-started/integration/app-lifecycle/#install-from-source

Please try again using the new instructions. It should be fixed now.

**Comment by xuezhaojun** [comment]
> Hi @xuezhaojun
> 
> https://open-cluster-management.io/getting-started/integration/app-lifecycle/#install-from-source
> 
> Please try again using the new instructions. It should be fixed now.

Yes, I have checked the issue is fixed now
