### ISSUE TITLE
Install Multicluster Subscription Operator from OperatorHub.io failed by lacking of resouce "KlusterletAddonConfig" on OKD

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/community#44]
Installing Application lifecycle management on OKD as [this document](https://open-cluster-management.io/getting-started/integration/app-lifecycle/#install-community-operator-from-operatorhubio) said:

Container multicluster-operators-argocdcluster-xxx start failed:

```
E0526 10:06:50.536999       1 manager.go:99] no matches for kind "KlusterletAddonConfig" in version "agent.open-cluster-management.io/v1"Manager exited non-zero
```

Fixed by install klusterlet CRD First.
See how to do it in : https://github.com/open-cluster-management/klusterlet-addon-controller

**Comment by mikeshng** [comment]
The set of functionalities for application lifecycle will change for the CNCF submission. Upcoming changes are:
- website update to https://open-cluster-management.io/getting-started/integration/app-lifecycle/ to reflect what functions will be supported 
- removal of operatorhub support install steps
- remove dependency for midstream specific code ie in this case `KlusterletAddonConfig`

Stay tune.

/assign mikeshng

**Comment by mikeshng** [comment]
hi @xuezhaojun
I think we can close this one because we no longer offer operatorhub install for this module.
see https://open-cluster-management.io/getting-started/integration/app-lifecycle
feel free to reopen if you disagree.
