### ISSUE TITLE
Clusteradm CLI

### ISSUE THREAD

**Issue by qiujian16** [open-cluster-management-io/community#51]
https://github.com/open-cluster-management-io/clusteradm

https://drive.google.com/file/d/1VCXusdZyVK7ls6Qz_jouPnza4WQeidr9/view

https://www.youtube.com/watch?v=7tdbuSXas3M

**Comment by mikeshng** [comment]
@xuezhaojun we have a few alpha releases of `clusteradm`. Could you please give it a try when you have some cycles?
https://github.com/open-cluster-management-io/clusteradm/releases/latest thanks

**Comment by xuezhaojun** [comment]
> @xuezhaojun we have a few alpha releases of `clusteradm`. Could you please give it a try when you have some cycles?
> https://github.com/open-cluster-management-io/clusteradm/releases/latest thanks

Sure.

**Comment by xuezhaojun** [comment]
> > @xuezhaojun we have a few alpha releases of `clusteradm`. Could you please give it a try when you have some cycles?
> > https://github.com/open-cluster-management-io/clusteradm/releases/latest thanks
> 
> Sure.

Clusteradm is ok using in the retest of application-lifecycle.

**Comment by qiujian16** [comment]
We might still need this track the progress of other clusteradm related items.

**Comment by zhujian7** [comment]
@qiujian16 can we close this now?
