### ISSUE TITLE
Placement enhancement: scheduling based on cluster capacity/resource usage

### ISSUE THREAD

**Issue by elgnay** [open-cluster-management-io/community#52]
When scheduling placement, select managed clusters based on cluster capacity or resource usage to balance the load cross the fleet.

**Comment by mikeshng** [comment]
to be discussed and decided later

**Comment by elgnay** [comment]
A draft proposal for this feature is available: https://docs.google.com/document/d/1066z0A7ZcCefsfDtbNKGGVSy2BPK5ZdZ-gHj5MxS-DY/edit?usp=sharing. Please share your feedback by creating comments on the doc.

**Comment by haoqing0110** [comment]
All necessary PRs are merged, mark as DONE.

**Comment by haoqing0110** [comment]
close as all the related work ([resource-based scheduling](https://github.com/open-cluster-management-io/enhancements/issues/15) and [extensible scheduling](https://github.com/open-cluster-management-io/enhancements/issues/32)) is done. 

/close
