### ISSUE TITLE
ginkgo: command not found

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/community#56]
### Related Repos:
https://github.com/open-cluster-management-io/config-policy-controller
https://github.com/open-cluster-management-io/governance-policy-template-sync
https://github.com/open-cluster-management-io/governance-policy-status-sync
https://github.com/open-cluster-management-io/governance-policy-spec-sync
https://github.com/open-cluster-management-io/governance-policy-propagator

### What Happened

Run `make e2e-test` and get an error:

```
ginkgo -v --slowSpecThreshold=10 test/e2e
/bin/bash: ginkgo: command not found
make: *** [e2e-test] Error 127
```

This is because we installed `ginkgo` under `.go/bin`, the default `GOBIN` set in Makefile.

```
GOPATH_DEFAULT := $(PWD)/.go
export GOPATH ?= $(GOPATH_DEFAULT)
GOBIN_DEFAULT := $(GOPATH)/bin
export GOBIN ?= $(GOBIN_DEFAULT)
```

Add `export PATH := $(PATH):$(GOBIN)` should fix this.

**Comment by nobody4t** [comment]
The PRs are here.
https://github.com/open-cluster-management-io/governance-policy-status-sync/pull/5/files
https://github.com/open-cluster-management-io/governance-policy-spec-sync/pull/5/files
https://github.com/open-cluster-management-io/governance-policy-propagator/pull/7/files
https://github.com/open-cluster-management-io/config-policy-controller/pull/8/files
https://github.com/open-cluster-management-io/governance-policy-template-sync/pull/5/files

**Comment by nobody4t** [comment]
All the PRs merged, close this issue.
@xuezhaojun plesae close this.
