### ISSUE TITLE
Download build-harness-bootstrap failed because of rate limiting

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/community#57]
### Related Repos

https://github.com/open-cluster-management-io/config-policy-controller
https://github.com/open-cluster-management-io/governance-policy-template-sync
https://github.com/open-cluster-management-io/governance-policy-status-sync
https://github.com/open-cluster-management-io/governance-policy-spec-sync
https://github.com/open-cluster-management-io/governance-policy-propagator

### What happened
Run `make build-image` failed, check the `.build-harness-bootstrap` get the following:

```
{"message":"API rate limit exceeded for 66.187.232.127. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

Check the Makefile and found we do download everytime run a command:

```
ifndef USE_VENDORIZED_BUILD_HARNESS
	ifeq ($(TRAVIS_BUILD),1)
	-include $(shell curl -H 'Accept: application/vnd.github.v4.raw' -L https://api.github.com/repos/open-cluster-management/build-harness-extensions/contents/templates/Makefile.build-harness-bootstrap -o .build-harness-bootstrap; echo .build-harness-bootstrap)
	endif
else
-include vbh/.build-harness-vendorized
endif
```

Is it possible to ignore the download part if the file already exist?

**Comment by mprahl** [comment]
I filed all the PRs but I don't have access to assign myself to this issue. Could someone please assign me?

**Comment by mikeshng** [comment]
/assign mprahl 

You can try typing the above next time and see if it works.

**Comment by mprahl** [comment]
All the PRs have been merged. I'll close this issue now.

**Comment by mprahl** [comment]
@xuezhaojun could you please close this issue?
