### ISSUE TITLE
`File exists` conflict for kubebuilder

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/community#58]
### Related Repos
https://github.com/open-cluster-management-io/config-policy-controller
https://github.com/open-cluster-management-io/governance-policy-template-sync
https://github.com/open-cluster-management-io/governance-policy-status-sync
https://github.com/open-cluster-management-io/governance-policy-spec-sync
https://github.com/open-cluster-management-io/governance-policy-propagator

### What happened

I run `make test-dependency` and get an error:
```
mv: cannot move '/tmp/kubebuilder_2.3.0_linux_amd64' to '/usr/local/kubebuilder/kubebuilder_2.3.0_linux_amd64': File exists
```

This is because I have test other repo before and I already run `make test-dependency` once.

Do we need to check whether the `/usr/local/kubebuilder/kubebuilder_2.3.0_linux_amd64` is existed before `mv` it?

**Comment by mikeshng** [comment]
I can probably help out with this one

/assign mikeshng

**Comment by mikeshng** [comment]
Hi @dhaiducek https://github.com/open-cluster-management-io/governance-policy-template-sync/pull/1 just missing this merge and then this issue can be resolved.

**Comment by dhaiducek** [comment]
Whoops--sorry I missed one! Merged!

**Comment by mikeshng** [comment]
@xuezhaojun please retest and I think this issue can be closed. Thanks.

**Comment by xuezhaojun** [comment]
> @xuezhaojun please retest and I think this issue can be closed. Thanks.

Retested, /lgtm

**Comment by mikeshng** [comment]
> > @xuezhaojun please retest and I think this issue can be closed. Thanks.
> 
> Retested, /lgtm

/close
