### ISSUE TITLE
Make deploy failed for `config-policy-controller`

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/community#61]
### Related Repo
https://github.com/open-cluster-management-io/config-policy-controller

#### First issue

I run `make deploy` and get an error:

```
make: `deploy' is up to date.
```

this should be fixed by adding `.PHONY: deploy` before:

```
deploy:
	kubectl apply -f deploy/ -n $(CONTROLLER_NAMESPACE)
	kubectl apply -f deploy/crds/ -n $(CONTROLLER_NAMESPACE)
	kubectl set env deployment/$(IMG) -n $(CONTROLLER_NAMESPACE) WATCH_NAMESPACE=$(WATCH_NAMESPACE)
```

#### Second issue

After adding `.PHONY`, it still not work and get an error:

```
error: unable to recognize "deploy/crds/policy.open-cluster-management.io_v1alpha1_configurationpolicy_cr.yaml": no matches for kind "ConfigurationPolicy" in version "policy.open-cluster-management.io/v1"
```

**Comment by mprahl** [comment]
I have a PR up for this at:
https://github.com/open-cluster-management-io/community/issues/61

I don't have access to assign issue this to myself.
