### ISSUE TITLE
Make lint failed for `config-policy-controller`

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/community#62]
### Related Repo
https://github.com/open-cluster-management-io/config-policy-controller

### What happened

I run `make lint` and get an error:

```
xargs: yamllint: No such file or directory
```

Do we need any pre-installation before `make lint`?

**Comment by mikeshng** [comment]
This is nice to fix but probably not urgent

/assign dhaiducek

**Comment by dhaiducek** [comment]
We don't really have linting implemented well (especially without the build-harness), so I'll remove it and replace it with `go fmt` in the README until we have something better.
