### ISSUE TITLE
GRC policy using Placement API

### ISSUE THREAD

**Issue by mikeshng** [open-cluster-management-io/community#63]
The current policy binding is using application management's PlacementRule API. It should support the Placement API instead because PlacementRule API is being deprecated. 

It will free up the "Application management" requirement from the policy framework. See https://open-cluster-management.io/getting-started/integration/policy-framework/#prerequisite

**Comment by gparvin** [comment]
@mikeshng @qiujian16 We can add placement support to the policy framework, but our [policy community](https://github.com/open-cluster-management/policy-collection) is still based on the application `PlacementRule` api.  Will existing applications or policies be able to work when the app apis are removed?  Is there some sort of webhook that does conversions from `PlacementRule` to `Placement`?

**Comment by jrnp7** [comment]
I have the same question as @gparvin - for example will policy files that current ACM customers have that contain stanza such as the following continue to work with placement API @mikeshng @qiujian16? We cannot break existing customer usage 

apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-etcdencryption
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}

**Comment by qiujian16** [comment]
I think it will need to support two apis at the same time for a certain time period until we are fully  confident to deprecate placementrule. 

For condition filters, we have an feature request in the community roadmap to add taint/toleration. So you in  the placement, you would not filter by a certain condition but tolerate whether a cluster is unreachable/unhealthy or not.

**Comment by jrnp7** [comment]
OK so you are confirming we will have backward compatibility for ACM 2.4 @qiujian16 :)

**Comment by qiujian16** [comment]
@jrnp7 yes.

**Comment by gparvin** [comment]
The Placement API is now supported in the policy propagator.

**Comment by dhaiducek** [comment]
Should this issue be closed?
