### ISSUE TITLE
Propagate application subscription to managed clusters using work API

### ISSUE THREAD

**Issue by mikeshng** [open-cluster-management-io/community#64]
For application subscription operator, deprecate the deployable API and start using the work API to propagate application hub subscription to all managed clusters.

This might improve the performance and scalability of the subscription operator.

**Comment by mikeshng** [comment]
@xiangjingli is the one that is actually prototyping/implementing this feature.

**Comment by xiangjingli** [comment]
here is same work logged for the midstream repo

https://github.com/open-cluster-management/backlog/issues/13991

**Comment by mikeshng** [comment]
Implemented and released in 0.5.0
