### ISSUE TITLE
Generate policies from standard resources to make creating policies easier

### ISSUE THREAD

**Issue by gparvin** [open-cluster-management-io/community#68]
Easily create ACM policies for various sources of policy:

Some sample sources of policies might include:
- k8s CRS e.g., roles, role bindings etc
- REGO policies enforced by OPA
- Kyverno policies
- etc 

The goal is to point to a source above and provide a placement detail, the this new tool can auto generate ACM policies. 

A script may be the starting point, and then a CLI could be integrated to enhance this.

**Comment by dhaiducek** [comment]
(To be presented at the Sept 30 community meeting)
