### ISSUE TITLE
Add trusted contributors to the open-cluster-management GitHub org

### ISSUE THREAD

**Issue by mikeshng** [open-cluster-management-io/community#7]
"To facilitate community members to easily contribute to the Open Cluster Management project, we need to find a way to securely add contributors to the open-cluster-management GitHub org." - @ray-harris

**Comment by qiujian16** [comment]
i do not think this is needed any longer

**Comment by juliana-hsu** [comment]
@qiujian16 @mikeshng Do we have a way to allow an external contributor to be an approver for PRs for open-cluster-management?  That is something we'll need to allow.

**Comment by mikeshng** [comment]
@juliana-hsu I think for now we are planning to use "GitHub Actions" instead of Openshift Org PROW to perform automated PR activities such as build, lint, check dco, function test, e2e test. For example, in https://github.com/open-cluster-management-io/registration-operator/pull/5 if you click "View details" you can see the automated steps that ran. 

In which case, we can have a trusted external contributor added to the user list of the repo and they will have the ability to approve and merge without any issues. Before, we use the openshift org prow so the user must be from the openshift github org.

@qiujian16 could you please confirm what I said above is true?

**Comment by juliana-hsu** [comment]
@qiujian16 @mikeshng I thought we were submitting open-cluster-management to CNCF based on Michael's request, and open-cluster-management-io was a temporary org before GA to make sure things worked?  Is that not the case?

**Comment by mikeshng** [comment]
@juliana-hsu `-io` is temporary in the sense that the name is temporary place holder. Prior to submitting to CNCF, we plan to:
1) rename the current ocm to something else
2) rename the `-io`to ocm

so all the work (repos, settings, prs, issues, comments) that are done in `-io` will not be impacted.
