### ISSUE TITLE
`go get` not working for policy framework

### ISSUE THREAD

**Issue by dhaiducek** [open-cluster-management-io/community#71]
```
go get -u github.com/open-cluster-management-io/governance-policy-propagator
go get: github.com/open-cluster-management-io/governance-policy-propagator@none updating to
	github.com/open-cluster-management-io/governance-policy-propagator@v0.0.0-20210617123451-284d7175be05: parsing go.mod:
	module declares its path as: github.com/open-cluster-management/governance-policy-propagator
	        but was required as: github.com/open-cluster-management-io/governance-policy-propagator
```

I'm thinking it won't work for our other repos either, but we'll need to verify:
- https://github.com/open-cluster-management-io/config-policy-controller
- https://github.com/open-cluster-management-io/governance-policy-propagator
- https://github.com/open-cluster-management-io/governance-policy-spec-sync
- https://github.com/open-cluster-management-io/governance-policy-status-sync
- https://github.com/open-cluster-management-io/governance-policy-template-sync

**Comment by mikeshng** [comment]
you might want to consider doing something like this:

https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/104
https://github.com/open-cluster-management-io/multicloud-operators-subscription/blob/main/go.mod#L39

This is how foundation and app repos avoid having to rename module to `github.com/open-cluster-management-io/...` but instead use module name that is more generic `module open-cluster-management.io/...`
