### ISSUE TITLE
Support calling API of the services running in management cluster directly from hub cluster (a.k.a push mode)

### ISSUE THREAD

**Issue by luckyfengyong** [open-cluster-management-io/community#73]
We have following use cases which requires calling K8s API or ingress endpoint of the services in managed cluster directly from hub cluster. 

1. Monitoring: Query current detailed status of the resource being provisioned
2. Maintenance with Out-of-Band: Agent in managed cluster used to retrieve kubernentes resource from hub cluster (a.k.a pull mode) does not work
3. Compatibility: Support application which used to work with "Kubefed" solution

A few open source projects support API proxy which could be leveraged in OCM to support push mode, such as ANP (https://github.com/kubernetes-sigs/apiserver-network-proxy), clusternet (https://github.com/clusternet/clusternet). Alternatively, it could be implemented in existing OCM component or introducing a new OCM component.

**Comment by apphe** [comment]
@yue9944882 Any progress for this one? Is it possible to fit into v0.6.0 release timeline?
