### ISSUE TITLE
Placement enhancement: Support enabled/disabled klusterlet addon in predicate clusterSelector match expression

### ISSUE THREAD

**Issue by tpouyer** [open-cluster-management-io/community#74]
## Summary
Placement should support match expression within the clusterSelector predicate that can operate against klusterlet addon enabled/disabled status.

## Example
I have a need to select managed clusters that have the `policyController` addon enabled because I want to utilize GRC policies to manage those clusters.  

Currently I cannot create a valid Placement that will accomplish this goal because klusterlet addon enabled/disabled status is not available for me to use in the match expression of the cluster selector.

**Comment by qiujian16** [comment]
we might consider implement something like this https://kubernetes-sigs.github.io/node-feature-discovery/v0.7/get-started/introduction.html.

So for each addon with available=true, we add an addon feature label

**Comment by qiujian16** [comment]
this one has been done with https://github.com/open-cluster-management-io/registration/pull/164
