### ISSUE TITLE
Managedcluster capacity included unscheduled worker node

### ISSUE THREAD

**Issue by zychina** [open-cluster-management-io/community#77]
In maintenance window, some worker nodes may be cordon as unscheduled to do some repair work, it may take a long time. When managedcluster calculate total capacity, these cordon worker nodes capacity should be removed.

Today, when I cordon some worker nodes in managedcluster, no capacity change in ManagedCluster CR status.
apiVersion: cluster.open-cluster-management.io/v1
  kind: ManagedCluster
metadata:
  name: managed-cluster1
status:
    allocatable:
      cpu: "8"
      memory: 13504Mi
    capacity:
      cpu: "8"
      memory: 15504Mi

**Comment by yue9944882** [comment]
my first thought is that we can have an external controller as an addon deployed in each managed-cluster which dynamically reports the latest nodes status via ClusterClaim api. and i will appreciate if you can expand the case detail on our weekly meeting,  thx!

**Comment by zychina** [comment]
The use case is when we do workload scheduling in multiple clusters, scheduler running on hub cluster needs to know capacity of each cluster to make scheduling decision.

**Comment by nobody4t** [comment]
@zychina

This should be related managed cluster. The resources info is updated in managedcluster status. And there is a delay to get to the desired state. 

Here when you `cordon` a node, this node will be labelled as `unschedulalbe`, but managed cluster currently can not process this. The node can still be accounted as available resource.  I think this is a bug for registration which handle managed cluster status update. 

I think you can open an issue agaist this.

**Comment by skeeey** [comment]
@zychina currently we list all nodes and get the capacity in registration controller, we may need a rule to calculate the cluster capacity or provide more capacity status
