### ISSUE TITLE
Placement enhancement: Support selecting globally scoped clusters

### ISSUE THREAD

**Issue by elgnay** [open-cluster-management-io/community#80]
There exist globally scoped managed clusters in OCM which don't belong to any clusterset. The Placement APIs need to support to select such kind of clusters as well.

**Comment by elgnay** [comment]
A draft enhancement proposal for this feature is available : https://docs.google.com/document/d/18OgH9Seb7Nq_fwCkGPy_sRunJkurfi5UuUOiLO2lYoM/edit?usp=sharing.

**Comment by ldpliu** [comment]
I think it should be done.
@elgnay please reopen if you have any concern
