### ISSUE TITLE
How to add ManagedCluster into multi ManagedClusterSet

### ISSUE THREAD

**Issue by youhangwang** [open-cluster-management-io/community#81]
To add a ManagedCluster to a ManagedClusterSet, user needs to set a label `cluster.open-cluster-management.io/clusterset={clusterset name}` on the ManagedCluster. 

Does this mean a ManagedCluster can not be added into multi ManagedClusterSet?

**Comment by nobody4t** [comment]
you can find an example in placement repos [readme](https://github.com/open-cluster-management-io/placement).

**Comment by youhangwang** [comment]
@dongwangdw thanks, but the example in readme only shows how to add the managed cluster into one clusterset by using:
```
...
  labels:
    cluster.open-cluster-management.io/clusterset: clusterset1
    vendor: OpenShift
...
```

To my understanding, you can't set two labels with the same key `cluster.open-cluster-management.io/clusterset`, for example:

```
...
  labels:
    cluster.open-cluster-management.io/clusterset: clusterset1
    cluster.open-cluster-management.io/clusterset: clusterset2
...
```

**Comment by youhangwang** [comment]
ocm doesn't support this case today.
