### ISSUE TITLE
NEW REPO: Create "cluster-proxy"

### ISSUE THREAD

**Issue by yue9944882** [open-cluster-management-io/community#82]
as the purpose and design stated in https://github.com/open-cluster-management-io/enhancements/pull/19, opening this ticket to request a new repo name "cluster-proxy" as a pluggable module in ocm that supports direct api calls from hub-> spoke cluster.

**Comment by qiujian16** [comment]
/assign @mdelder 

+1 I am good to create this repo.

**Comment by qiujian16** [comment]
done
