### ISSUE TITLE
Apply to be a OCM member

### ISSUE THREAD

**Issue by suigh** [open-cluster-management-io/community#87]
Community Participant
Asked some questions and replied some messages on slack channel "#open-cluster-mgmt"

Initialized some features/enhancement and contribute ideas like add [a user scenario ......](https://github.com/open-cluster-management-io/open-cluster-management-io.github.io/pull/135), [update placement API with PrioritizerConfigs](https://github.com/open-cluster-management-io/api/pull/93)

Contributed some bug fixed at placement, registration, community.

Requirements
- Enabled [two-factor authentication] on their GitHub account 
   Yes
- Have made multiple contributions to the project or community.  Contribution may include, but is not limited to:
   		- Authoring or reviewing PRs on GitHub
   		- Filing or commenting on issues on GitHub
		- Contributing to documentation, blogs, tutorials
		- Contributing to test automation
   	- Contributing to community discussions (e.g. meetings, Slack, mailing list discussion)
   Yes
- Subscribed to [https://groups.google.com/g/open-cluster-management]
   Yes
- Have read the [contributor guide]
  Yes
- Actively contributing to 1 or more subprojects.
  Yes
- Sponsored by 2 reviewers. **Note the following requirements for sponsors**:
     - Sponsors must have close interactions with the prospective member,  e.g.   code/design/proposal review, coordinating  on issues, etc.
     - Sponsors must be reviewers or approvers in at least 1 OWNERS file in any repo in the  [Open-Cluster-Management org], or the org they are sponsoring for.
     - An approver/reviewer in the [Open-Cluster-Management org] may sponsor someone for the [Open-Cluster-Management org]
     or any of the related [Open-Cluster-Management GitHub organizations]; as long as it's a project they're involved with.
   - Sponsors must be from multiple member companies to demonstrate integration across the community. 
     Yes. Talked with Yuan Yuan and Jian, they are OK for this application.
- **[Open an issue][membership request] against the Open-Cluster-Management/community repo**
  - Ensure your sponsors are @mentioned on the issue
  - Complete every item on the checklist
  - Make sure that the list of contributions included is representative of your work on the project.
    Yes
- Have your sponsoring reviewers reply confirmation of sponsorship: `+1`
- Once your sponsors have responded, your request will be reviewed by the [Open-Cluster-Management GitHub Admin team]. Any missing information will be requested.

Do we need any of this template info?
Continues to contribute regularly, as demonstrated by having at least [TODO: Number] [TODO: Metric] a year, as demonstrated by [TODO: contributor metrics source].  ->  placement, registration, community.
[TODO: Number] accepted PRs, -> 4
Reviewed [TODO: Number] PRs, -> 4
Resolved and closed [TODO: Number] Issues, -> 4
Must have been contributing for at least [TODO: Number] months -> 3

**Comment by suigh** [comment]
@qiujian16  :)

**Comment by qiujian16** [comment]
Done, thanks for your contribution!
