### ISSUE TITLE
Apply to be a OCM member

### ISSUE THREAD

**Issue by wangglbj** [open-cluster-management-io/community#88]
Community Participant
 Asked some questions and replied some messages on slack channel "#open-cluster-mgmt"
 Review some problems in the document and fix these errors like this [Modify the incorrect URL link](https://github.com/open-cluster-management-io/governance-policy-propagator/pull/13) ,  [Modify the incorrect format](https://github.com/open-cluster-management-io/placement/pull/33)

Contributed some bug fixed at governance-policy-status-sync, clusteradm, community.

Requirements

- Enabled [two-factor authentication] on their GitHub account
  Yes

- Have made multiple contributions to the project or community.  Contribution may include, but is not limited to:

  \- Reviewing PRs on GitHub

  \- Filing or commenting on issues on GitHub

  \- Build OCM test environment

  \- FIX Related problems in the test environment

  \- Contributing to documentation, blogs, tutorials

  \- Contributing to test automation

  - Contributing to community discussions (e.g. meetings, Slack, mailing list discussion)
    Yes

- Subscribed to [https://groups.google.com/g/open-cluster-management]
  Yes

- Have read the [contributor guide]
  Yes

- Actively contributing to 1 or more subprojects.
  Yes

- Sponsored by 2 reviewers. 

  Note the following requirements for sponsors:
  - Sponsors must have close interactions with the prospective member,   e.g.   code/design/proposal review, coordinating  on issues, etc.
  - Sponsors must be reviewers or approvers in at least 1 OWNERS file in any repo in the  [Open-Cluster-Management org], or the org they are  sponsoring for.
  - An approver/reviewer in the [Open-Cluster-Management org] may sponsor someone for the [Open-Cluster-Management org]
    or any of the related [Open-Cluster-Management GitHub organizations]; as long as it's a project they're involved with.
  - Sponsors must be from multiple member companies to demonstrate integration across the community.
    Yes. Talked with Yuan Yuan and Jian, they are OK for this application.

- [Open an issue][membership request] against the Open-Cluster-Management/community repo

  - Ensure your sponsors are @mentioned on the issue
  - Complete every item on the checklist
  - Make sure that the list of contributions included is representative of your work on the project.
    Yes

- Have your sponsoring reviewers reply confirmation of sponsorship: `+1`

- Once your sponsors have responded, your request will be reviewed by  the [Open-Cluster-Management GitHub Admin team]. Any missing information will be requested.

Do we need any of this template info?
 Continues to contribute regularly, as demonstrated by having at least  [TODO: Number] [TODO: Metric] a year, as demonstrated by [TODO:  contributor metrics source].  ->  governance-policy-status-sync, clusteradm, community.
 [TODO: Number] accepted PRs, -> 2
 Reviewed [TODO: Number] PRs, -> 2
 Resolved and closed [TODO: Number] Issues, -> 2
 Must have been contributing for at least [TODO: Number] months -> 3

**Comment by wangglbj** [comment]
@qiujian16 :)

**Comment by wangglbj** [comment]
@qiujian16 :)

**Comment by qiujian16** [comment]
done, thanks for your contribution!
