### ISSUE TITLE
New repo: `policy-generator-plugin`

### ISSUE THREAD

**Issue by dhaiducek** [open-cluster-management-io/community#89]
We'd like to create the `policy-generator-plugin` repo to migrate code to upstream for issue:
- #68

**Comment by dhaiducek** [comment]
(To be presented at the Sept 30 community meeting)

**Comment by qiujian16** [comment]
Based on the discussion in community Sep. 30, We would consider a repo like `ocm-kustomize-generator-plugin`, and it can be used for policy generator/manifestwork generator and further.

**Comment by dhaiducek** [comment]
New repo created: https://github.com/open-cluster-management-io/ocm-kustomize-generator-plugins
